# Inspired by: https://github.com/wazuh/wazuh-docker/blob/v4.0.0_1.10.1/docker-compose.yml

# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)
version: '3.7'

services:
  wazuh:
    image: wazuh/wazuh-odfe:4.0.0_1.10.1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      # In a non-demo deployment we wouldn't place secrets in the Dockerfile
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.10.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: wazuh/wazuh-kibana-odfe:4.0.0_1.10.1
    hostname: kibana
    restart: always
    ports:
      - 8080:5601
    environment:
      # Inspired by: https://github.com/wazuh/wazuh-docker/blob/v4.0.0_1.10.1/docker-compose.yml
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/opendistroforelasticsearch.example.org.cert
      - SERVER_SSL_KEY=/usr/share/kibana/config/opendistroforelasticsearch.example.org.key
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  victim:
    image: zachroofsec/c2-with-merlin-victim
    build: ./victim-container
    container_name: victim
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    links:
      - wazuh:wazuh
      - merlin-server:merlin-server

    depends_on:
      - wazuh
      - merlin-server

  merlin-server:
    image: zachroofsec/c2-with-merlin-merlin-server
    build: ./merlin-server-container/
    container_name: merlin-server
    ports:
      - "443:443"

